module.exports = {
  projects: [
    '<rootDir>/apps/admin-web',
    '<rootDir>/apps/client-web',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api/lib1',
    '<rootDir>/libs/api/lib2',
    '<rootDir>/libs/api/lib3',
    '<rootDir>/libs/api/lib4',
    '<rootDir>/libs/api/lib5',
    '<rootDir>/libs/admin-web/lib1',
    '<rootDir>/libs/admin-web/lib2',
    '<rootDir>/libs/admin-web/lib3',
    '<rootDir>/libs/admin-web/lib4',
    '<rootDir>/libs/admin-web/lib5',
    '<rootDir>/libs/client-web/lib5',
    '<rootDir>/libs/client-web/lib4',
    '<rootDir>/libs/client-web/lib3',
    '<rootDir>/libs/client-web/lib2',
    '<rootDir>/libs/client-web/lib1',
  ],
};
